openapi: 3.0.0
info:
    title: SOUND-BASED BIRD CLASSIFICATION API
    description: API de prédiction de l'espèce d'un oiseau basé sur son chant
    version: 1.0.0
servers:
    - url: http://localhost:8080/v1
paths:
    /birds/prediction:
      post:
        summary: Renvoie l'espèce de l'oiseau prédite
        description: Renvoie l'espèce détectée, le taux de confiance de la prédiction
        requestBody:
          description: Fichier audio du chant de l'oiseau
          required: true
          content:
            audio/*:
              schema:
                type: string
                format: binary
        responses:
            "200":
                description: Retourne un objet json contenant l'espèce détectée, le taux de confiance de la prédiction
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Prediction"
components:
  schemas:
    Prediction:
      type: object
      properties:
        specie:
          type: string
        rate:
          type: number