# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Sound(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, binary: str=None):  # noqa: E501
        """Sound - a model defined in Swagger

        :param binary: The binary of this Sound.  # noqa: E501
        :type binary: str
        """
        self.swagger_types = {
            'binary': str
        }

        self.attribute_map = {
            'binary': 'binary'
        }
        self._binary = binary

    @classmethod
    def from_dict(cls, dikt) -> 'Sound':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Sound of this Sound.  # noqa: E501
        :rtype: Sound
        """
        return util.deserialize_model(dikt, cls)

    @property
    def binary(self) -> str:
        """Gets the binary of this Sound.


        :return: The binary of this Sound.
        :rtype: str
        """
        return self._binary

    @binary.setter
    def binary(self, binary: str):
        """Sets the binary of this Sound.


        :param binary: The binary of this Sound.
        :type binary: str
        """

        self._binary = binary
