openapi: 3.0.0
info:
    title: API de classification de sons urbains
    description: API de prédiction de la source d'un bruit provenant d'une ville
    version: 1.0.0
servers:
    - url: http://localhost:8080/v1
paths:
    /sounds/prediction:
      post:
        summary: Renvoie une prédiction de la source du bruit
        description: Renvoie la source détectée et le taux de confiance de la prédiction
        requestBody:
          description: Fichier audio du son
          required: true
          content:
            audio/*:
              schema:
                type: string
                format: binary
        responses:
            "200":
                description: Retourne un objet json contenant la source prédite et son taux de confiance
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Prediction"
components:
  schemas:
    Prediction:
      type: object
      properties:
        source:
          type: string
        rate:
          type: number